### ISSUE TITLE
get_magic_quotes_gpc

### ISSUE THREAD

**Issue by maddrid** [mindstellar/Osclass#287]
**Describe the bug**

Warning

This function has been DEPRECATED as of PHP 7.4.0. Relying on this function is highly discouraged.

**Comment by navjottomer** [comment]
Where? In dev branch?

**Comment by maddrid** [comment]
master . at least make it compatible  with 7.4 ?
or  focus on dev ?

**Comment by eurobank** [comment]
@maddrid 

Maybe come up with a 3.9.1 fix with a few hand selected bug-fixes (like this one) ?

**Comment by navjottomer** [comment]
I am finalizing the new build with working automatic update as beta, it will be released with all the commits in the dev branch.
With that, we can push small updates easily. 
Current 3.x.x ( Including original osclass builds and the variant of them) are vulnerable to XSS and SQL injection attacks and take time to fix, which will withdraw our focus from 4.x branch (or name it 5.x due to multiple cheap attempt of copying our master branch repository code and released it as 4.x name with some modifications).
The new branch is faster, secure with added features like automatic updates, new JS libraries, easy location and language installation. With auto-update, the new release will be easy to support in future.
I will draft a beta release and everyone will work on that for a full stable release.

Let me know, how does it sound.

**Comment by eurobank** [comment]
Sounds great.

**Comment by Teurn** [comment]
Sound great, love your work so much

**Comment by dev-101** [comment]
>or name it 5.x due to multiple cheap attempts of copying our master branch repository code and released it as 4.x name with some modifications

I have come across that version, ironically, their code is not public (ironically) and further changes they did additionally broke compatibility with existing plugins and themes (well, same as the 'our' version did, but even more), and that will be the most problematic thing for those who will just _overwrite the files_. And my guess will be that there will be such cases, and when things break it will be messy.

I asked one person why upgraded, the answer received was 'because that was the newest version' 😄 

Users should be warned that compatibility does not exist and that they do not overwrite any code blidly.

**Comment by eurobank** [comment]
@dev101 Yes, even 3.9 breaks thing and nobody cares to fix them. If the next version of "yours" breaks even more themes and plugins, then it won't be nice. And to be honest those are so small and easy problems to fix, if some devs cared,

**Comment by dev-101** [comment]
Well, I have fixed mines and luckily they were only minor issues, but it is not realistic to expect a fix for everything, I don't know almost anyone from the old project that maintains or work anymore on Osclass (I consider in that category myself for the time being), past those pirates mentioned above.

Also, after the change to new version, compatibility will only get worse in some cases, impossible to fix without more changes. It is not a good situation, far from ideal. In any case, those who have active projects / work will definitely have to invest into maintenance, for sure.

**Comment by navjottomer** [comment]
> @dev101 Yes, even 3.9 breaks thing and nobody cares to fix them. If the next version of "yours" breaks even more themes and plugins, then it won't be nice. And to be honest those are so small and easy problems to fix, if some devs cared,

I do care about people who use my code ( work ??) but I have to keep a check on my available time and put it into more important things. Initially, I thought some old collaborators will help me in that regard but I can't blame anyone as everyone has to earn their living, it is really hard to invest your time for free and more so in current time.
 
For compatibility issue, I always try to not introduce anything which breaks compatibility with older plugins and themes but there is no guarantee and sometimes they have to adapt. If someone is interested in old plugins and theme than stay with 3.9.x with its flaws or copy-paste code from new branch where it has been already fixed.
I am certain that with the future release I'll be more comfortable to fix things on a daily bases then it is now.

> I asked one person why upgraded, the answer received was 'because that was the newest version' 😄
> 

😄  😄  😄  😄

**Comment by dev-101** [comment]
Regarding fix for this issue, in case someone wants to do it manually, get_magic_quotes_gpc() will always return false, so for now nothing should be done. Eventually, every part in Osclass (4 core files) should remove all the if conditions where this functions is used and simply do nothing. There is no replacement required.

**Comment by eurobank** [comment]
@dev-101

Can you please explain a bit better what to do with 3.9 and get_magic_quotes and PHP 7.4 ?

**Comment by dev-101** [comment]
Any instance of get_magic_quotes_gpc should be removed.

Some plugins might be using it (in fact, I am sure some probably do), and the way it is implemented in them might be different, simply because there are many variations of writing php code, but the point is the same, since this functions hasn't been used in years since PHP 5.4 or later.

Now, one typical example inside Osclass core, which should cover the basics, is this one:

```
if(get_magic_quotes_gpc()) {
	$value = strip_slashes_extended($value);
}
```

Simply delete entire code section exactly as above and you are good. There are 4 (5 if you count readme.php) files in 3.8 version, and I assume it is the same in 3.90 that needs this little intervention.
