### ISSUE TITLE
5.1 beta 2: scripts_loaded hook not being called

### ISSUE THREAD

**Issue by alastairR** [mindstellar/Osclass#390]
Pre 5.0 versions ran hook scripts_loaded, and this was changed to admin_header_scripts_loaded in 5.0, but no scripts_loaded hook is being called at all in 5.1 beta 2

**Comment by navjottomer** [comment]
Do you mean, scripts_loaded hook in the backend?

**Comment by alastairR** [comment]
I mean for the frontend theme. Enqueued scripts are loaded and in 3.x there
was a scripts_loaded hook that was called immediately after for both admin
and frontend, and for 5.0 I had to add hooks for
admin_header_scripts_loaded for admin and header_scripts_loaded for
frontend, but 5.1 does not seem to call any variation of scripts_loaded. I
have worked around by adding a admin_header and header hook to call my
scripts_loaded function but it would be better to have a separate
scripts_loaded hook called.

**Comment by navjottomer** [comment]
Was a bug. 

more changes are made for new behaviour see: 32744c084bd8a64be0c2c8d18d0f6151bf5e2315
old `admin_header_scripts_loaded`, `header_scripts_loaded`, `admin_footer_scripts_loaded`, `footer_scripts_loaded` are deprecated in  favor of` admin_scripts_loaded`, `scripts_loaded`. 
They'll still work till fully removed in future releases, a deprecated warning will trigger on use of these old hooks.
Now `admin_scripts_loaded` and `scripts_loaded` hook will always run in the footer, it's simple to remember only two hooks, instead of my previous implementation.
I hope it makes more sense, but these are not final yet, you can share your suggestions.

**Comment by alastairR** [comment]
Sorry, I'm still not able to get my admin_scripts_loaded or scripts_loaded hooks to be called.
I thought it might be because I'd set up my plugin as a class that encloses all the hook functions, and the constructor adding all the hooks and filters, with each hook being passed an array with &$this and the function name. But even moving the function to the index.php and putting the add hooks in there made no difference.
Using the admin_header or header hooks gets the function called.

**Comment by navjottomer** [comment]
Thanks for the heads-up, I'll check again.

**Comment by navjottomer** [comment]
Okay, I checked, my fault again. While I was testing I set the priority of hook to default and it was working. Then I changed it to 20 which I didn't realize that it is higher than the for-loop limit set in Plugins class. Fixed now.
