### ISSUE TITLE
5.1b2 - TinyMCE User editor shows html codes while editing an ad

### ISSUE THREAD

**Issue by eurobank** [mindstellar/Osclass#410]
After an ad is posted, a User editing his ad he sees html codes along with the body of the ad. 

![Screenshot](https://user-images.githubusercontent.com/4467158/135734372-bf617bea-865c-4f32-83b3-e1f362ca11db.png)

**This DOESN'T happen with the Admin editing with TinyMCE.**

**Comment by dftd** [comment]
Osclass 5.0.2

```html
<textarea>&lt;p&gt;&lt;strong&gt;Bold text&lt;/strong&gt;&lt;/p&gt;</textarea>
```

Osclass 5.1b2

```html
<textarea>&amp;lt;p&amp;gt;&amp;lt;strong&amp;gt;Bold text&amp;lt;/strong&amp;gt;&amp;lt;/p&amp;gt;</textarea>
```

The `&amp` looks the be the main problem. Something with sanitization classes I'd guess, but couldn't find the exact problem yet.

**Comment by eurobank** [comment]
And why it shows ONLY to the User TinyMCE and not in the Admin edit?

**Comment by navjottomer** [comment]
The issue is that all forms are generated through a new `FormInputs` class, which by default escape HTML(aka sanitize) in textarea, but in themes, this is done in user views. Like bender theme use osc_esc_html over osc_item_description while creating Textarea input.
With new classes, it's easy to just change ` sanitize=>null` via the options argument to disable it.
Three ways we can go with it.
1. Disable default sanitization in Textarea. But disabling by default means most developers will overlook this feature, return security risk.
2. Removing the `osc_esc_html` where this issue occurs.  We have to edit every theme which uses this implementation.
3. Disable it in the `ItemForm` class  via the option, which keeps this security concern to item description only
4. Disable it in Generic Text-area method in `Form` class which will disable this for any textArea which use this method ( means 99% text area input are at mercy of theme/plugin developer.)

What do you suggest? For me best compromise is number 3.

**Comment by dftd** [comment]
I'm not sure between 2 or 3.

As we're adding more features, themes will have to adapt more and more, just like with this. Maybe stick with that path and keep it to theme developers. We can add a notice or something. 
Bender should be updated to contain all that new changes/features we implement, at least for other developers to have some reference, although I don't know anyone that actively develops themes and doesn't have their own Osclass fork.

3. is an okay workaround, but it's just that, a workaround...


P.S. On a similar note, please take a look at https://github.com/mindstellar/Osclass/issues/211, where I ask about implementing cookie & gdpr notices as a part of the core or leaving it to theme devs.

**Comment by eurobank** [comment]
@navjottomer Why this only happens when Editing an ad and not after the 1st save/post of the ad?

**Comment by dftd** [comment]
> @navjottomer Why this only happens when Editing an ad and not after the 1st save/post of the ad?

Form class sanitizes the value of an input/textarea before filling it. On edit page, the input is automatically filled from item data in database. On publish page, the user is the one entering the data.

**Comment by eurobank** [comment]
@dftd Ok, got it. So when editing an ad, the issue is (as you say) in the initial load/filling of the item data. Does the SAVE of that editied ad also perform the same check? I guess it does? If so, what is the risk sking the 1st check?

**Comment by eurobank** [comment]
Such fondamental changes will continue to break each and every plugin and theme, from the few left that are working. 

And since nobody will fix those (understandable), and since we can't even buy one right now, nobody is gonna even test those releases. 

So that mean no audience (webmasters that will use it). A great script, and advanced script that nobody CAN use.

**Comment by navjottomer** [comment]
Yup, that's why option 3 is best for the current situation.

**Comment by navjottomer** [comment]
Done.
